In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
frame = pd.read_csv("train.csv")

In [3]:
print(frame.shape)
frame.head()

(20800, 5)


id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
frame.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [5]:
frame = frame.fillna(' ')
frame['total'] = frame['title']+' '+frame['author']+frame['text']
frame

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  \
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1      Ever get the feeling your life circles the rou...      0   
2      Why the Truth Might Get You Fired October 29, ...      1   
3      Videos 15 Civilians Killed In Single US Airstr...      1   
4      Print \nAn Iranian woman has been sentenced to...      1   
...                                                  ...    ...   
20795  Rapper T. I. unloaded on black celebrities who...      0   
20796  When the Green Bay Packers lost to the Washing...      0   
20797  The Macy’s of today grew from the union of sev...      0   
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1   
20799    David Swanson is an author, activist, journa...      1   

                                                   total  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2      Why the Truth Might Get You Fired Consortiumne...  
3      15 Civilians Killed In Single US Airstrike Hav...  
4      Iranian woman jailed for fictional unpublished...  
...                                                  ...  
20795  Rapper T.I.: Trump a ’Poster Child For White S...  
20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...  
20797  Macy’s Is Said to Receive Takeover Approach by...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799  What Keeps the F-35 Alive David Swanson  David...  

[20800 rows x 6 columns]

In [6]:
frame.isnull().sum()

id        0
title     0
author    0
text      0
label     0
total     0
dtype: int64

In [7]:
frame = frame.set_index("id")
frame.head()

title              author  \
id                                                                          
0   House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2                   Why the Truth Might Get You Fired  Consortiumnews.com   
3   15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                 text  label  \
id                                                             
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1   
1   Ever get the feeling your life circles the rou...      0   
2   Why the Truth Might Get You Fired October 29, ...      1   
3   Videos 15 Civilians Killed In Single US Airstr...      1   
4   Print \nAn Iranian woman has been sentenced to...      1   

                                                total  
id                                                     
0   House Dem Aide: We Didn’t Even See Comey’s Let...  
1   FLYNN: Hillary Clinton, Big Woman on Campus - ...  
2   Why the Truth Might Get You Fired Consortiumne...  
3   15 Civilians Killed In Single US Airstrike Hav...  
4   Iranian woman jailed for fictional unpublished...

In [8]:
frame=frame.drop(["title", 'author'],axis=1)
frame1=frame.drop(['total'],axis=1)

In [9]:
frame1

text  label
id                                                             
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1
1      Ever get the feeling your life circles the rou...      0
2      Why the Truth Might Get You Fired October 29, ...      1
3      Videos 15 Civilians Killed In Single US Airstr...      1
4      Print \nAn Iranian woman has been sentenced to...      1
...                                                  ...    ...
20795  Rapper T. I. unloaded on black celebrities who...      0
20796  When the Green Bay Packers lost to the Washing...      0
20797  The Macy’s of today grew from the union of sev...      0
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1
20799    David Swanson is an author, activist, journa...      1

[20800 rows x 2 columns]

In [10]:
print(frame1.isnull().sum())

text     0
label    0
dtype: int64


In [11]:
y = frame1.label
print(y)

id
0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 20800, dtype: int64


In [12]:
frame1.drop("label", axis=1)
frame1.head()

text  label
id                                                          
0   House Dem Aide: We Didn’t Even See Comey’s Let...      1
1   Ever get the feeling your life circles the rou...      0
2   Why the Truth Might Get You Fired October 29, ...      1
3   Videos 15 Civilians Killed In Single US Airstr...      1
4   Print \nAn Iranian woman has been sentenced to...      1

In [13]:
import re
import string
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text) 
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)    
    return text

In [14]:
frame1["text"] = frame["text"].apply(wordopt)

In [15]:
frame1.head()

text  label
id                                                          
0   house dem aide  we didn t even see comey s let...      1
1   ever get the feeling your life circles the rou...      0
2   why the truth might get you fired october     ...      1
3   videos  civilians killed in single us airstrik...      1
4   print  an iranian woman has been sentenced to ...      1

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(frame['text'], y, test_size=0.25, random_state=43)

In [17]:
X_train

id
14469    WASHINGTON  —   The Supreme Court on Thursday ...
684      LOS ANGELES  —   Foreign governments concerned...
5165     It’s 4 p. m. on a cold December Friday. I type...
15555    Some would say that the true stars of this yea...
2151     Google Pinterest Digg Linkedin Reddit Stumbleu...
                               ...                        
18448                                          Innocent...
7985     0 Add Comment \nA NATO general has warned toda...
18687    License DMCA Racism is generally thought of as...
19776    WASHINGTON  —   President Obama is delaying a ...
14148    (Want to get this briefing by email? Here’s th...
Name: text, Length: 15600, dtype: object

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7) 
tfidf_train = tfidf_vectorizer.fit_transform(X_train)

tfidf_test = tfidf_vectorizer.transform(X_test)

In [19]:
from sklearn.naive_bayes import MultinomialNB
MNB = MultinomialNB() 
MNB.fit(tfidf_train, y_train)
pred = MNB.predict(tfidf_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, pred)
print(cm)
score = accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)

[[2529   30]
 [ 708 1933]]
accuracy:   0.858


In [20]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state = 0)
LR.fit(tfidf_train, y_train )
pred = LR.predict(tfidf_test)
cm = confusion_matrix(y_test, pred)
print(cm)
score = accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)

[[2395  164]
 [ 118 2523]]
accuracy:   0.946


In [21]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors = 1000)
KNN.fit(tfidf_train, y_train)
pred = KNN.predict(tfidf_test)
cm = confusion_matrix(y_test, pred)
print(cm)
score = accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)

[[2298  261]
 [ 386 2255]]
accuracy:   0.876


In [22]:
from sklearn.linear_model import PassiveAggressiveClassifier
PA = PassiveAggressiveClassifier(random_state=0)
PA.fit(tfidf_train, y_train)
pred = PA.predict(tfidf_test)
cm = confusion_matrix(y_test, pred)
print(cm)
score = accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)

[[2451  108]
 [  99 2542]]
accuracy:   0.960


# Passive Aggressive Classifier is giving the most accurate score.